<?php

// $Id$

/**
 *@file
 * Mucking about with the aggregator module
 * 
 */

/**
 *  Implements hook_block_info()
 */
function ncpedia_agg_block_info() {
  $blocks['nchistory'] = array(
      'info' => t('This Day in North Carolina History'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function ncpedia_agg_block_view($delta='') {
  $block['subject'] = t('This Day in North Carolina History');
  $block['content'] = ncpedia_agg_block_contents($delta);
  
  return $block;
}

function ncpedia_agg_block_contents($which_block) {
  
  if ($which_block === 'nchistory') {
    $return_str = '';

    $query = db_select('aggregator_item', 'ai') 
      ->fields('ai', array('title', 'link', 'description'))     
      ->condition('fid', 2)
      ->orderBy('iid', 'DESC')
      ->range(0,5)
      ->addTag('node access');
    $result = $query->execute();
    
    $firstrow = TRUE;
    foreach($result as $row) {
      //Grab image, if available
      $img_src = '';
      if (preg_match('/\<img.+?src="(.+?)".+?\/>/si', $row->description, $img_matches)) {
        $img_src = '<div class="nchistory-agg-pic"><img src="' . $img_matches[1] . '" style="height:100px;" /></div>';
      }
      //Grab first two sentences for the text snippet. This is sorta flaky. It would get
      //tripped up by "Ft." or "St." or "Rd." etc. and cut off mid-sentence or be very short. 
      //Or, it could get quite long. So if the snippet is especially short or long, just take 
      //130 characters, find the next word break, and cut it off there.
      $snippet = '';
      if (preg_match('/On\s.+?\..+?\./s', strip_tags($row->description), $text_matches)) {
        //Start the snippet with a div wrapper, set the text content to the regex match
        $snippet = '<div class="nchistory-agg-headline">';
        $snippet_text = $text_matches[0];
        //If the text is especially long, try just one sentence instead
        if (strlen($snippet_text) > 250) {
          $snippet_text = substr($snippet_text, 0, stripos($snippet_text, '. ') + 1);
        }
        //Now make sure the regex match or its shorter version isn't especially short either.
        //If it is, just grab the first 130 characters (or so; stop at a word break) of the
        //original match and append an ellipsis
        if (strlen($snippet_text) < 60) {
          $new_length = strlen($text_matches[0]) > 130 ? 130 : strlen($text_matches[0]);          
          $snippet .= substr($text_matches[0], 0, stripos($text_matches[0], ' ', $new_length)) . '...';
        }
        else {
          $snippet .= $snippet_text;  
        }
        $snippet .= '</div>';
      }
      if ($firstrow) {
        $firstrow = FALSE;
        $return_str .= '<p class="nchistory-agg-item-today">' . l($row->title, $row->link) . '</p>';
        $return_str .= $img_src . $snippet;
        $return_str .= '<p class="nchistory-agg-item-old">Previous days: ';
      }
      else {
        $return_str .= l($row->title, $row->link) . ' | ';
      }  
    }
    $return_str .= '<a href="http://nchistorytoday.wordpress.com/">More...</a></p>';

    return $return_str; 
  }
}


//Page-creation function
//Currently disabled
//
//function ncpedia_agg_menu() {
//
//  $items['agg'] = array(
//    'page callback' => 'ncpedia_agg_page',     
//    'access arguments' => array('access content'),
//    'type' => MENU_CALLBACK,
//  );  
//  return $items;
//}
//function ncpedia_agg_page(){
//  
//  $return_str = '<p></p><p></p><p></p><div id="block-ncpedia_agg-nchistory">';
//  
//      $query = db_select('aggregator_item', 'ai') 
//      ->fields('ai', array('title', 'link', 'description'))     
//      ->condition('fid', 2)
//      ->orderBy('iid', 'DESC')
//      ->range(1,5)
//      ->addTag('node access');
//    $result = $query->execute();
//    $firstrow = TRUE;
//    
//    $t = 'On January 17, 1874, St. Bill was knighted. He was good.';
//       
//    
//    foreach($result as $row) {
//      $img_src = '';
//      $first_sentence = '';
//      if (preg_match('/\<img.+?src="(.+?)".+?\/>/si', $t, $img_matches)) {
//        $img_src = '<div class="nchistory-agg-pic"><img src="' . $img_matches[1] . '" style="height:100px;" /></div>';
//      }
//      if (preg_match('/\On\s?\<b\>.+?\s[a-z]+\./s', strip_tags($t), $fs_matches)) {
//        $first_sentence = '<div class="nchistory-agg-headline">' . $fs_matches[0] . '</div>';
//      }
//      if ($firstrow) {
//        $firstrow = FALSE;
//        $return_str .= '<p class="nchistory-agg-item-today">' . l($row->title, $row->link) . '</p>';
//        $return_str .= $img_src . $first_sentence;
//        $return_str .= '<p class="nchistory-agg-item-old">Previous days: ';
//      }
//      else {
//        $return_str .= l($row->title, $row->link) . ' | ';
//      }  
//    }
//    $return_str .= '<a href="http://nchistorytoday.wordpress.com/">More...</a></p></div>';
//
//    return $return_str; 
//    
//}